/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mikolab_Jni_Rtimu */

#ifndef _Included_com_mikolab_Jni_Rtimu
#define _Included_com_mikolab_Jni_Rtimu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mikolab_Jni_Rtimu
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mikolab_Jni_Rtimu_init
  (JNIEnv *, jobject);

/*
 * Class:     com_mikolab_Jni_Rtimu
 * Method:    getPollInterval
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mikolab_Jni_Rtimu_getPollInterval
  (JNIEnv *, jobject);

/*
 * Class:     com_mikolab_Jni_Rtimu
 * Method:    getReadings
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_mikolab_Jni_Rtimu_getReadings
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
